import assert from "node:assert/strict";
import fs from "node:fs";
import { search, terms, ranked, briefing } from "../src/pulse/search.ts";
const catalog = JSON.parse(fs.readFileSync(new URL("../src/pulse/catalog.json",import.meta.url),"utf8"));
const cache = {...catalog, changes:[], benchmarks:[]};
assert.deepEqual(terms("Free AI for making videos"),["video"]);
const video = search(cache,"Free AI for making videos");
assert.ok(video.tools.some(t=>t.id==="runway"));
assert.ok(video.tools.every(t=>t.freeTier&&t.categories.includes("Video")));
assert.ok(!video.tools.some(t=>t.id==="gemini"));
const compare = search(cache,"GPT vs Claude for React");
assert.ok(compare.comparison&&compare.models.some(m=>m.company==="OpenAI")&&compare.models.some(m=>m.company==="Anthropic"));
const now=Date.parse("2026-10-05T12:00:00Z");
const article=(id,company,days,impact="Update")=>({id,company,title:`${company} coding update`,summary:"",published:new Date(now-days*86400000).toISOString(),tags:["Coding"],impact,kind:"news"});
const news=[article("a","OpenAI",1),article("b","OpenAI",2),article("c","Anthropic",3,"High"),article("d","Google",4),article("old","OpenAI",40),article("future","OpenAI",-2)];
const matches=search({...cache,articles:news},"What happened with OpenAI this week?",now);
assert.deepEqual(matches.articles.map(a=>a.id),["a","b"]);
const brief=briefing(news,now);
assert.ok(brief.length<=5&&new Set(brief.slice(0,3).map(a=>a.company)).size===3);
assert.ok(!brief.some(a=>a.id==="old"||a.id==="future"));
assert.equal(search(cache,"zzzzqnotfound").tools.length,0);
const benchmarks=[{name:"A (low)",company:"X",intelligence:1,speed:10,cost:2},{name:"A (high)",company:"X",intelligence:3,speed:5,cost:3},{name:"B",company:"Y",intelligence:2,speed:20,cost:1}];
assert.deepEqual(ranked({...cache,benchmarks},"Intelligence").map(b=>b.name),["A (high)","B"]);
assert.equal(ranked({...cache,benchmarks},"Cost per task")[0].name,"B");
console.log("AI Pulse: local retrieval, free tools, dated news, comparisons, briefing variety and benchmark grouping passed.");
