//! Characters you import yourself: any picture (an anime hero, a game
//! character, your cat). Glowby shows it as a small round icon with all his
//! moods, hats and auras. Glowby ships no pictures of its own; yours stay in
//! %APPDATA%\dev.glowby.app\characters and are never uploaded anywhere.
//!
//! The crop happens in the Settings page (the browser engine decodes the
//! picture); Rust only stores the finished 256×256 PNG and checks it really is one.

use crate::settings;
use crate::state::{self, AppState, lock};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};

/// Pictures larger than this are refused before reading (a 4K PNG is ~10 MB).
const MAX_SOURCE_BYTES: u64 = 30 * 1024 * 1024;
/// The cropped icon Settings sends back (256×256 PNG is ~50–200 KB).
const MAX_ICON_BYTES: usize = 2 * 1024 * 1024;
const MAX_ICON_SIDE: u32 = 1024;
const MAX_CHARACTERS: usize = 60;
const MAX_NAME_CHARS: usize = 40;

#[derive(Serialize, Deserialize, Clone, Debug, Default)]
#[serde(default, rename_all = "camelCase")]
pub struct CharacterInfo {
    pub id: String,
    pub name: String,
    pub added: String,
}

#[derive(Serialize, Deserialize, Default)]
#[serde(default)]
pub struct Characters {
    pub list: Vec<CharacterInfo>,
}

impl Characters {
    pub fn exists(&self, id: &str) -> bool {
        !id.is_empty() && self.list.iter().any(|c| c.id == id)
    }
}

/// What kind of picture the first bytes say this is (we never trust the file extension).
pub fn sniff_image(bytes: &[u8]) -> Option<&'static str> {
    let starts = |sig: &[u8]| bytes.starts_with(sig);
    if starts(b"\x89PNG\r\n\x1a\n") {
        Some("png")
    } else if starts(b"\xFF\xD8\xFF") {
        Some("jpeg")
    } else if starts(b"GIF87a") || starts(b"GIF89a") {
        Some("gif")
    } else if bytes.len() >= 12 && &bytes[0..4] == b"RIFF" && &bytes[8..12] == b"WEBP" {
        Some("webp")
    } else if starts(b"BM") {
        Some("bmp")
    } else {
        None
    }
}

/// Width and height from a PNG's header chunk (IHDR), if this is a PNG.
fn png_size(bytes: &[u8]) -> Option<(u32, u32)> {
    if sniff_image(bytes) != Some("png") || bytes.len() < 24 || &bytes[12..16] != b"IHDR" {
        return None;
    }
    let w = u32::from_be_bytes(bytes[16..20].try_into().ok()?);
    let h = u32::from_be_bytes(bytes[20..24].try_into().ok()?);
    Some((w, h))
}

/// Ids are generated by Glowby; anything else is refused, so an id can never
/// point outside the characters folder ("..\..\something").
fn valid_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 40 && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

fn clean_name(name: &str, fallback: &str) -> String {
    let cleaned: String = name.chars().filter(|c| !c.is_control()).collect::<String>().trim().chars().take(MAX_NAME_CHARS).collect();
    if cleaned.is_empty() { fallback.to_string() } else { cleaned }
}

/// "%E4%BA%94 Gojo" → "五 Gojo" (names travel in an HTTP-style header, which must be ASCII).
pub fn percent_decode(text: &str) -> String {
    let bytes = text.as_bytes();
    let hex = |b: &u8| (*b as char).to_digit(16);
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%'
            && let (Some(h), Some(l)) = (bytes.get(i + 1).and_then(hex), bytes.get(i + 2).and_then(hex))
        {
            out.push((h * 16 + l) as u8);
            i += 3;
        } else {
            out.push(bytes[i]);
            i += 1;
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn image_path(state: &AppState, id: &str) -> PathBuf {
    state.paths.characters_dir.join(format!("{id}.png"))
}

fn save_list(state: &AppState) {
    let list = lock(&state.characters);
    if let Err(e) = settings::save_json(&state.paths.characters_file, &*list) {
        crate::applog::line(format!("couldn't save characters.json: {e}"));
    }
}

pub fn list(app: &AppHandle) -> Vec<CharacterInfo> {
    lock(&app.state::<AppState>().characters).list.clone()
}

/// Reads a picture you picked in Settings so the page can crop it.
pub fn read_source(path: &str) -> Result<Vec<u8>, String> {
    let path = Path::new(path);
    let meta = std::fs::metadata(path).map_err(|_| "Couldn't open that file.".to_string())?;
    if !meta.is_file() {
        return Err("That isn't a file.".into());
    }
    if meta.len() > MAX_SOURCE_BYTES {
        return Err("That picture is too big (over 30 MB).".into());
    }
    let bytes = std::fs::read(path).map_err(|e| format!("Couldn't read that file: {e}"))?;
    if sniff_image(&bytes).is_none() {
        return Err("That doesn't look like a picture (PNG, JPG, GIF, WebP or BMP).".into());
    }
    Ok(bytes)
}

/// Stores a cropped icon (PNG bytes) as a new character.
pub fn add(app: &AppHandle, name: &str, png: &[u8]) -> Result<CharacterInfo, String> {
    let state = app.state::<AppState>();
    if png.len() > MAX_ICON_BYTES {
        return Err("The cropped picture is too large.".into());
    }
    match png_size(png) {
        Some((w, h)) if w > 0 && h > 0 && w <= MAX_ICON_SIDE && h <= MAX_ICON_SIDE => {}
        _ => return Err("That isn't a valid PNG picture.".into()),
    }
    let count = lock(&state.characters).list.len();
    if count >= MAX_CHARACTERS {
        return Err(format!("You can keep up to {MAX_CHARACTERS} characters. Delete one first."));
    }
    let now = chrono::Local::now();
    let base = format!("c{}", now.format("%Y%m%d-%H%M%S%3f"));
    let mut id = base.clone();
    for n in 2.. {
        if !lock(&state.characters).exists(&id) && !image_path(&state, &id).exists() {
            break;
        }
        id = format!("{base}-{n}");
    }
    let info = CharacterInfo { id: id.clone(), name: clean_name(name, &format!("Character {}", count + 1)), added: now.to_rfc3339() };
    std::fs::create_dir_all(&state.paths.characters_dir).map_err(|e| e.to_string())?;
    let path = image_path(&state, &id);
    let tmp = path.with_extension("png.tmp");
    std::fs::write(&tmp, png).and_then(|_| std::fs::rename(&tmp, &path)).map_err(|e| format!("Couldn't save the picture: {e}"))?;
    lock(&state.characters).list.push(info.clone());
    save_list(&state);
    crate::applog::line(format!("character imported: {id}"));
    Ok(info)
}

pub fn rename(app: &AppHandle, id: &str, name: &str) -> Result<(), String> {
    let state = app.state::<AppState>();
    {
        let mut chars = lock(&state.characters);
        let c = chars.list.iter_mut().find(|c| c.id == id).ok_or("No such character.")?;
        c.name = clean_name(name, &c.name.clone());
    }
    save_list(&state);
    state::publish(app);
    Ok(())
}

/// Deletes the picture and stops using it anywhere (Glowby, squad pets).
pub fn delete(app: &AppHandle, id: &str) -> Result<(), String> {
    if !valid_id(id) {
        return Err("No such character.".into());
    }
    let state = app.state::<AppState>();
    lock(&state.characters).list.retain(|c| c.id != id);
    save_list(&state);
    let _ = std::fs::remove_file(image_path(&state, id));
    let mut s = state.settings();
    if s.pet.character == id {
        s.pet.character.clear();
        state.save_settings(s);
    }
    crate::squad::forget_character(app, id);
    state::publish(app);
    Ok(())
}

/// The stored icon, for the pet window and Settings to draw.
pub fn image(app: &AppHandle, id: &str) -> Result<Vec<u8>, String> {
    let state = app.state::<AppState>();
    if !valid_id(id) || !lock(&state.characters).exists(id) {
        return Err("No such character.".into());
    }
    std::fs::read(image_path(&state, id)).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pictures_are_recognised_by_content_not_name() {
        assert_eq!(sniff_image(b"\x89PNG\r\n\x1a\n...."), Some("png"));
        assert_eq!(sniff_image(b"\xFF\xD8\xFF\xE0.."), Some("jpeg"));
        assert_eq!(sniff_image(b"RIFF\0\0\0\0WEBPVP8 "), Some("webp"));
        assert_eq!(sniff_image(b"GIF89a.."), Some("gif"));
        assert_eq!(sniff_image(b"-----BEGIN OPENSSH PRIVATE KEY-----"), None);
        assert_eq!(sniff_image(b""), None);
    }

    #[test]
    fn png_header_gives_the_size() {
        let mut png = b"\x89PNG\r\n\x1a\n\0\0\0\x0dIHDR".to_vec();
        png.extend_from_slice(&256u32.to_be_bytes());
        png.extend_from_slice(&200u32.to_be_bytes());
        assert_eq!(png_size(&png), Some((256, 200)));
        assert_eq!(png_size(b"\xFF\xD8\xFF"), None);
    }

    #[test]
    fn ids_cannot_escape_the_folder() {
        assert!(valid_id("c20261001120000-42"));
        assert!(!valid_id(r"..\..\secrets"));
        assert!(!valid_id("a/b"));
        assert!(!valid_id(""));
    }

    #[test]
    fn names_are_decoded_and_cleaned() {
        assert_eq!(percent_decode("Gojo%20Satoru"), "Gojo Satoru");
        assert_eq!(percent_decode("%E4%BA%94"), "五");
        assert_eq!(percent_decode("100%"), "100%");
        assert_eq!(clean_name("  Luffy\n ", "x"), "Luffy");
        assert_eq!(clean_name("   ", "Character 3"), "Character 3");
        assert_eq!(clean_name(&"a".repeat(100), "x").len(), MAX_NAME_CHARS);
    }
}
